name: Brain-Games-CI

on:
  push:
    branches: 
      - '**'

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14.x, 17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          make install
        env:
          CI: true  
      - name: Run Linter
        run: |
          make lint